### ISSUE TITLE
Importing spatial satellite sea surface temperature data

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#20]
Want the same resulting structure as for ROMS data, so wait until that aspect is finalised. So we can then use same tailored plotting functions.

See emails with Andrea Hilborn (6/5/23) regarding her https://github.com/IOS-OSD-DPG/Pacific_SST_Monitoring

**Comment by andrew-edwards** [comment]
Time series from buoys are now done as `buoy_sst`.

**Comment by andrew-edwards** [comment]
Looks like the OISST values (actual temperatures and anomalies) would be best (yes Andrea @schckngs ? ), from Andrea's GitHub above. It gets updated every week (data are already in an .rds file). We could ideally save weekly data unless that's too big. 
I think we will commit to updating pacea once a month (see ideas on #25).

I just saw the marine heatwave data as well - that would be useful so I can incorporate that as it'll just be time series. 

I looked at the email train I mentioned above (6/5/23) but there's nothing relevant to here (more to do with the buoy data).

@travistai2 - sound good? Andrea already has data saved as .rds, so hopefully it will just be case of confining to our area of interest.

**Comment by travistai2** [comment]
Excellent! Will get on this.

**Comment by travistai2** [comment]
Looking through the data and scripts on Andrea's repo, the only data she keeps is the most recent week of data and the climatology for the 7 day period (1991-2020). 

The data are from NOAA, https://coastwatch.pfeg.noaa.gov/erddap/index.html, which we could write a code similar to Andrea's to update the SST data (monthly?). The OISST data go back to 1981.

**Comment by andrew-edwards** [comment]
Okay. Probably worth just using her code to get and save what we want. I think it's all in there, just make her a co-author on any functions (she's an author of our package). Ideally best not to have two different sets of 'data extraction' functions in two places, but may be unavoidable here. Plus we don't need to get data for such a big area as she is using. 
1981 is awesome.

**Comment by andrew-edwards** [comment]
Realised I did a similar thing for the buoys data - adapted Andrea's code. See `?buoy_sst` for how I referenced her work - seems the way to go.

**Comment by schckngs** [comment]
Hey all, sorry for the late reply (github notifications got lost). If there are additional layers that can be kept / grabbed on the Pacific SST page let me know :) We can discuss more tomorrow, cheers
