### ISSUE TITLE
When to commit to updating the data in pacea?

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#25]
For ongoing data streams, I'm thinking once a month, running some of the code in `data-raw`.

Say the 16th to ensure getting the latest `mei` (updated on 10th of month if source data are available), and `oni` (updated first Thursday of each month). 

`buoy_sst` is updated on an ongoing basis, so once a month would be good. Also add instructions (clone, run data-raw) if someone really wants the most up-to-date values.

ROMS outputs will be annual as available.

**Comment by travistai2** [comment]
AFter what Charles and co. said, I think we agreed on quarterly?

**Comment by andrew-edwards** [comment]
Yes, monthly might be a bit much. How about 16th of every second month and see how that goes. And we can say that if someone really wants the latest, say, `buoy_sst` we can probably meet that request.

**Comment by andrew-edwards** [comment]
Go for 16th of every month - will capture the previous OISST month. Probably....

**Comment by andrew-edwards** [comment]
Closed in a85c6c7.
