### ISSUE TITLE
Please check that math (10^6 km^2) renders properly in Rstudio help for ?alpi

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#29]
Doesn't render properly for me, but nor does `?rpois`. Please check at some point (once I've pushed), then can close this. Thanks.

**Comment by seananderson** [comment]
The RStudio help should just be the HTML help files. This looks helpful: https://stackoverflow.com/questions/3782337/mathematical-notion-superscripts-in-rd-files

**Comment by andrew-edwards** [comment]
Thanks. I'm not using RStudio though, so can't check. I get it rendered in plain text, which is fine for me.

**Comment by seananderson** [comment]
```r 
help("glm", help_type = "html")
help("glm", help_type = "pdf")
```

should work

**Comment by travistai2** [comment]
Check it and it looks good. Noticed a typo "APLI" instead of "ALPI" in the 'anomaly' description. Issue can be closed
