### ISSUE TITLE
Create pacea_roms object that contains all available ROMS outputs 

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#32]
i.e. like `pacea_indices`. 

- [x] create `pacea_roms`
- [x] Then we write a wrapper to loop round the object names to run `get_pacea_data()` for every ROMS output. Then in the vignette tell people to either use the wrapper (which might take a while and use up some disk space), or to use the individual `get_pacea_data()` with one of the `pacea_roms` values as the argument.

- [x] Can also add an automated table to the ROMS vignette.

- [x] May also want to save a smaller ROMS output (e.g. six years for a small region) in pacea to facilitate testing? My new `spatial_average()` function needs such an object as input, so will need something for testing. Probably worth doing if not too big. Though I see Travis has this https://github.com/pbs-assess/pacea/blob/d1b3a3ab3b43aaa3f9640a0716094f528a37399a/tests/testthat/test-plot-pacea-st.R#L8  for testing, but then each test needs to download an SST file. Maybe we should save one in `pacea`, can be `roms_sst_example` for just six years and a restricted area.

**Comment by travistai2** [comment]
I think this can be closed now. 
- There is a `bccm_data` object that list all available data layers. 
- `bccm_all_variables()` downloads all layers.
- Automated table in the ROMS vignette is just the `bccm_data` object?
- I created a smaller data set for testing (`test_surftemp.rds`), which I will update in the testing files. (I will add this as a todo in my 'todo issue')
