### ISSUE TITLE
In help for data objects, the source should contain the file that is sourced to build the data object

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#41]
Do you mind adding these please? Presumably all in data.R. 

For example, I'm trying to see where `bccm_data` is made, and `?bccm_data` does not tell me (and I can't see it in `data-raw/roms/`).

I was wondering about re-ordering the variable names, and was just curious about where it was built. Thanks.

**Comment by travistai2** [comment]
Ahh no worries. I updated the document. It's in the `data-raw/data-key` folder and my script is data-list.R and data-list.csv. I think the other files were Joe's?
