### ISSUE TITLE
Add function for users to see when they last installed the package

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#46]
This should pretty much work, just need to make it into a function:
```
paste0(.libPaths(), "/pacea/DESCRIPTION"))$ctime %>% lubridate::as_date()
```

Think it should be platform independent. People can then compare the date with the latest update to the package.

**Comment by seananderson** [comment]
or `packageVersion("pacea")`

**Comment by andrew-edwards** [comment]
Done with `pacea_installed()` [avoids having to always update package version], and added to talk and README.
